name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t devops-demo .

    - name: Test Docker image
      run: docker run --rm devops-demo python -m unittest || echo "No tests"

    - name: Deploy to Render (or other platform)
      run: echo "Deployment step here"
